// Official-registry coverage gate: every command Khronos publishes for
// OpenGL ES 3.2 / EGL 1.5 must resolve + map in TGL, or the test names it.
//
// Ground truth (NOT TGL's own lists):
//   tests/cts/official_es32.inc + official_egl.inc, generated by
//   tools/cts/sync_official.py from the LIVE Khronos registries
//   (OpenGL-Registry gl.xml features GL_ES_VERSION_{2_0,3_0,3_1,3_2},
//    EGL-Registry egl.xml features EGL_VERSION_1_{0..5}).
// Verified 2026-09-22: live registry yields EXACTLY 358 GLES + 44 EGL names,
// matching docs/reference/gl32.h (358 GL_APICALL) and TGL's
// kCoreEntryPointCount/kCoreProcNameCount (358). The 2 extra EGL names
// MobileGL requires (eglSwapBuffersWithDamageEXT, eglUnlockSurfaceKHR) are
// platform EXT/KHR additions, also gated here.
//
// When this test goes red, the printf lines name the exact missing API:
// add the dispatch body (gl_real.cpp/egl_api.cpp), the Metal route
// (metal_mapping.cpp) and the execution/validation before claiming support.

#include "test_framework.h"

#include <dlfcn.h>

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "tgles/base/spec.h"
#include "tgles/gpu/metal_mapping.h"
#include "tgles/host/entry_points.h"

#ifndef TGLES_HOST_LIBRARY_PATH
#define TGLES_HOST_LIBRARY_PATH "./libtgles.dylib"
#endif

namespace {

const char* const kOfficialGles[] = {
#include "official_es32.inc"
};

const char* const kOfficialEgl[] = {
#include "official_egl.inc"
};

// MobileGL loader extras beyond EGL 1.5 core (verified: both are EXT/KHR
// platform additions, served by TGL's egl_api.cpp).
const char* const kMobileGlEglExtras[] = {
    "eglSwapBuffersWithDamageEXT",
    "eglUnlockSurfaceKHR",
};

void* HostLibrary() {
  static void* handle = dlopen(TGLES_HOST_LIBRARY_PATH, RTLD_NOW | RTLD_LOCAL);
  return handle;
}

typedef void* (*GetProcFn)(const char*);

}  // namespace

TEST(OfficialCoverage, LiveRegistryCountsMatchInternalConstants) {
  // The live Khronos registries must agree with the vendored headers and
  // TGL's own constants. A Khronos publication that changes these counts
  // turns this red on purpose (re-run sync_official.py and read the diff).
  EXPECT_EQ(sizeof(kOfficialGles) / sizeof(kOfficialGles[0]),
            static_cast<std::size_t>(358));
  EXPECT_EQ(tgles::kCoreEntryPointCount, static_cast<std::size_t>(358));
  EXPECT_EQ(tgles::kCoreProcNameCount, static_cast<std::size_t>(358));
  EXPECT_EQ(sizeof(kOfficialEgl) / sizeof(kOfficialEgl[0]),
            static_cast<std::size_t>(44));
}

TEST(OfficialCoverage, EveryOfficialGlesResolvesInBuiltLibrary) {
  void* lib = HostLibrary();
  EXPECT_TRUE(lib != nullptr);
  if (lib == nullptr) return;
  auto get_proc =
      reinterpret_cast<GetProcFn>(dlsym(lib, "eglGetProcAddress"));
  EXPECT_TRUE(get_proc != nullptr);
  if (get_proc == nullptr) return;
  std::size_t missing_dlsym = 0, missing_proc = 0;
  for (const char* name : kOfficialGles) {
    if (dlsym(lib, name) == nullptr) {
      if (missing_dlsym < 20) std::printf("  dlsym NULL for %s\n", name);
      ++missing_dlsym;
    }
    if (get_proc(name) == nullptr) {
      if (missing_proc < 20) std::printf("  procaddr NULL for %s\n", name);
      ++missing_proc;
    }
  }
  std::printf("  official GLES: %zu checked, %zu dlsym-missing, %zu "
              "procaddr-missing\n",
              sizeof(kOfficialGles) / sizeof(kOfficialGles[0]), missing_dlsym,
              missing_proc);
  EXPECT_EQ(missing_dlsym, std::size_t{0});
  EXPECT_EQ(missing_proc, std::size_t{0});
}

TEST(OfficialCoverage, EveryOfficialGlesHasMetalMapping) {
  std::size_t unmapped = 0;
  for (const char* name : kOfficialGles) {
    const tgles::metal::FeatureMapping* m =
        tgles::metal::FindMapping(name);
    if (m == nullptr) {
      if (unmapped < 20) std::printf("  NO Metal mapping for %s\n", name);
      ++unmapped;
    }
  }
  std::printf("  official GLES mappings: %zu checked, %zu unmapped\n",
              sizeof(kOfficialGles) / sizeof(kOfficialGles[0]), unmapped);
  EXPECT_EQ(unmapped, std::size_t{0});
}

TEST(OfficialCoverage, EveryOfficialEglResolvesPlusMobileGlExtras) {
  void* lib = HostLibrary();
  EXPECT_TRUE(lib != nullptr);
  if (lib == nullptr) return;
  auto get_proc =
      reinterpret_cast<GetProcFn>(dlsym(lib, "eglGetProcAddress"));
  EXPECT_TRUE(get_proc != nullptr);
  if (get_proc == nullptr) return;
  std::size_t missing = 0;
  for (const char* name : kOfficialEgl) {
    if (dlsym(lib, name) == nullptr || get_proc(name) == nullptr) {
      if (missing < 20) std::printf("  EGL missing: %s\n", name);
      ++missing;
    }
  }
  // The 2 MobileGL loader extras beyond EGL 1.5 core.
  for (const char* name : kMobileGlEglExtras) {
    if (dlsym(lib, name) == nullptr || get_proc(name) == nullptr) {
      std::printf("  MobileGL EGL extra missing: %s\n", name);
      ++missing;
    }
  }
  std::printf("  official EGL: %zu + %zu extras checked, %zu missing\n",
              sizeof(kOfficialEgl) / sizeof(kOfficialEgl[0]),
              sizeof(kMobileGlEglExtras) / sizeof(kMobileGlEglExtras[0]),
              missing);
  EXPECT_EQ(missing, std::size_t{0});
}

TEST(OfficialCoverage, ExecutedVsEmulatedKindsStayHonest) {
  using tgles::metal::MappingKind;
  const auto* m = tgles::metal::FindMapping("glDispatchCompute");
  EXPECT_TRUE(m != nullptr);
  if (m != nullptr) EXPECT_TRUE(m->kind == MappingKind::kDirect);
  // Indirect compute reads groups from the DISPATCH_INDIRECT store, then the
  // direct marker-gated execution (indirect groups are no longer tracked).
  m = tgles::metal::FindMapping("glDispatchComputeIndirect");
  EXPECT_TRUE(m != nullptr);
  if (m != nullptr) EXPECT_TRUE(m->kind == MappingKind::kDirect);
  // MRT / multisample resolve validate CPU-side only (no bridge execution).
  for (const char* n :
       {"glDrawBuffers", "glReadBuffer", "glBlitFramebuffer"}) {
    m = tgles::metal::FindMapping(n);
    EXPECT_TRUE(m != nullptr);
    if (m != nullptr) EXPECT_TRUE(m->kind == MappingKind::kEmulated);
  }
}
