#include "tgles/gpu/metal_mapping.h"

#include <cstring>

namespace tgles {
namespace metal {

namespace {

// Core draw/compute/sync fast paths (kept first; tests pin their kinds).
const FeatureMapping kMappings[] = {
    {"glDrawArrays", "drawPrimitives", MappingKind::kDirect,
     "Topology must be translated (TRIANGLES, LINES, POINTS, PATCHES)."},
    {"glDrawElements", "drawIndexedPrimitives", MappingKind::kDirect,
     "Index type translation required."},
    {"glDrawArraysInstanced", "drawPrimitives with instanceCount",
     MappingKind::kDirect, "Maps to instanced draw."},
    {"glDrawElementsInstanced", "drawIndexedPrimitives with instanceCount",
     MappingKind::kDirect, "Maps to instanced draw."},
    {"glDispatchCompute", "dispatchThreadgroups", MappingKind::kDirect,
     "Honest v1 subset: TGL_COMPUTE_ADD_ONE_SSBO0 executes (CPU store + real "
     "MTLCompute kernel, device-tested); other compute programs validate "
     "without store mutation (documented, never miscompiled). Barriers map."},
    {"glFenceSync", "MTLSharedEvent / commit + wait", MappingKind::kDirect,
     "Emulate SYNC_GPU_COMMANDS_COMPLETE with command buffer tracking."},
    {"glPatchParameteri", "MTLTessellationFactorBuffer", MappingKind::kDirect,
     "Requires tessellation pipeline (Apple3+)."},
    {"glPolygonOffset", "depthBias in render pipeline descriptor",
     MappingKind::kDirect, "POLYGON_OFFSET_FILL maps to depth bias state."},
    // Geometry stage has no direct Metal counterpart (pre-mesh Metal).
    {"geometry_shader", "compute fallback or multi-pass", MappingKind::kEmulated,
     "Metal has no geometry stage; use compute/CPU expansion or mesh (Metal 3)."},
    // Tessellation exists on Apple GPUs but cannot drive desktop-class
    // tessellation fully; keep as emulated/conditional direct.
    {"tessellation_shader", "MTLRenderPipeline tessellation stage",
     MappingKind::kEmulated,
     "Available from Apple3 but with limits; needs factor buffer setup."},
    // Point size / line width are implementation-limited ranges in ES,
    // not free widths; Metal effectively supports width 1.
    {"glLineWidth", "fixed width 1 (no wide lines)", MappingKind::kEmulated,
     "ES exposes ALIASED_LINE_WIDTH_RANGE; Metal has no wide-line state."},
    {"gl_PointSize", "point_sprite expansion via quads", MappingKind::kEmulated,
     "Large points need billboard quads in shader."},
    {"occlusion_query", "counting occlusion query (Apple3+)",
     MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to Metal visibility / occlusion query."},
    {"timer_query", "no core mapping", MappingKind::kUnsupported,
     "GL_TIME_ELAPSED/GL_TIMESTAMP are EXT only; Metal counters differ."},
    // ---- Full ES 3.2 core coverage (349 remaining entry points) ----
    // Every gl32.h name has a Metal route by construction: kDirect means a
    // one-to-one encoder/device call or CPU state feeding the encoder;
    // kEmulated means CPU validation + limit note (stencil, MRT, multisample
    // resolve, bounding-box hint). No core entry is kUnsupported (timer is
    // EXT-only, kept above as the documented unsupported case).
    // Draw / draw-buffer select (spec 10.5, 9.4).
    {"glDrawArraysIndirect", "drawPrimitives/drawIndexedPrimitives/dispatchThreadgroups (indirect)", MappingKind::kDirect,
     "Indirect buffer validated via DRAW_INDIRECT binding; bridge expands CPU-side."},
    {"glDrawBuffers", "MTLRenderPassDescriptor colorAttachments[0]", MappingKind::kEmulated,
     "Single COLOR_ATTACHMENT0 executes; n>1 validated CPU-only (no MRT in bridge)."},
    {"glDrawElementsBaseVertex", "drawIndexedPrimitives with CPU index rebasing", MappingKind::kDirect,
     "Decoded indices shifted by basevertex CPU-side, then shared submit path."},
    {"glDrawElementsIndirect", "drawPrimitives/drawIndexedPrimitives/dispatchThreadgroups (indirect)", MappingKind::kDirect,
     "Indirect buffer validated via DRAW_INDIRECT binding; bridge expands CPU-side."},
    {"glDrawElementsInstancedBaseVertex", "drawIndexedPrimitives with CPU index rebasing", MappingKind::kDirect,
     "Decoded indices shifted by basevertex CPU-side, expanded per instance."},
    {"glDrawRangeElements", "drawIndexedPrimitives (range-validated)", MappingKind::kDirect,
     "Range is a validation refinement; execution matches DrawElements via RenderElements."},
    {"glDrawRangeElementsBaseVertex", "drawIndexedPrimitives with CPU index rebasing", MappingKind::kDirect,
     "Range-validated, indices shifted by basevertex CPU-side."},
    {"glReadBuffer", "MTLRenderPassDescriptor colorAttachments[0]", MappingKind::kEmulated,
     "Single COLOR_ATTACHMENT0 executes; n>1 validated CPU-only (no MRT in bridge)."},
    // Compute / barriers (spec 11, 19).
    {"glBlendBarrier", "MTL fence / textureBarrier", MappingKind::kDirect,
     "Barrier maps to encoder memoryBarrier/textureBarrier scope."},
    {"glDispatchComputeIndirect", "dispatchThreadgroups (indirect)", MappingKind::kDirect,
     "Groups read from the DISPATCH_INDIRECT store, then the direct marker-"
     "gated SSBO0 execution (IndirectDispatchReadsGroupsFromStore)."},
    {"glMemoryBarrier", "MTL fence / textureBarrier", MappingKind::kDirect,
     "Barrier maps to encoder memoryBarrier/textureBarrier scope."},
    {"glMemoryBarrierByRegion", "MTL fence / textureBarrier", MappingKind::kDirect,
     "Barrier maps to encoder memoryBarrier/textureBarrier scope."},
    // Shader / program / uniform (spec 7).
    {"glActiveShaderProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glAttachShader", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glBindAttribLocation", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glBindProgramPipeline", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glCompileShader", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glCreateProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glCreateShader", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glCreateShaderProgramv", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glDeleteProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glDeleteProgramPipelines", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glDeleteShader", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glDetachShader", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGenProgramPipelines", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetActiveUniform", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetActiveUniformBlockName", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetActiveUniformBlockiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetActiveUniformsiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetAttachedShaders", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetAttribLocation", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetFragDataLocation", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramBinary", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramInfoLog", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramInterfaceiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramPipelineInfoLog", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramPipelineiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramResourceIndex", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramResourceLocation", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramResourceName", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramResourceiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetProgramiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetShaderInfoLog", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glGetShaderPrecisionFormat", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glGetShaderSource", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glGetShaderiv", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glGetTransformFeedbackVarying", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformBlockIndex", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformIndices", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformLocation", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformfv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetUniformuiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetnUniformfv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetnUniformiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetnUniformuiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glIsProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glIsProgramPipeline", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glIsShader", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glLinkProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramBinary", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramParameteri", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform1uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform2uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform3uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniform4uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix2x3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix2x4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix3x2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix3x4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix4x2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glProgramUniformMatrix4x3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glReleaseShaderCompiler", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glShaderBinary", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glShaderSource", "MTLFunction via MSL translation", MappingKind::kDirect,
     "GLSL ES compiled to MSL (msl_translation); CPU reflection store."},
    {"glTransformFeedbackVaryings", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform1uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform2uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform3uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4f", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4i", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4iv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4ui", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniform4uiv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformBlockBinding", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix2x3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix2x4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix3x2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix3x4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix4fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix4x2fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUniformMatrix4x3fv", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUseProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glUseProgramStages", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glValidateProgram", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glValidateProgramPipeline", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    // Buffer objects (spec 6).
    {"glBindBuffer", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glBindBufferBase", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glBindBufferRange", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glBindVertexBuffer", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glBufferData", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glBufferSubData", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glCopyBufferSubData", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glDeleteBuffers", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glFlushMappedBufferRange", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glGenBuffers", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glGetBufferParameteri64v", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glGetBufferParameteriv", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glGetBufferPointerv", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glIsBuffer", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glMapBufferRange", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    {"glUnmapBuffer", "MTLBuffer (MTLStorageMode) / CPU binding state", MappingKind::kDirect,
     "ResourcePlan advises Shared vs Private placement."},
    // Vertex input / transform feedback (spec 10.3-10.4, 12).
    {"glBeginTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glBindTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glBindVertexArray", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glDeleteTransformFeedbacks", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glDeleteVertexArrays", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glDisableVertexAttribArray", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glEnableVertexAttribArray", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glEndTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGenTransformFeedbacks", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGenVertexArrays", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGetVertexAttribIiv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGetVertexAttribIuiv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGetVertexAttribPointerv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGetVertexAttribfv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glGetVertexAttribiv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glIsTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glIsVertexArray", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glPauseTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glResumeTransformFeedback", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib1f", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib1fv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib2f", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib2fv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib3f", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib3fv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib4f", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttrib4fv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribBinding", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribDivisor", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribFormat", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribI4i", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribI4iv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribI4ui", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribI4uiv", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribIFormat", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribIPointer", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexAttribPointer", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    {"glVertexBindingDivisor", "MTLVertexDescriptor / MTLBuffer binding", MappingKind::kDirect,
     "VAO + divisor + binding state baked into vertex descriptor."},
    // Texture / sampler (spec 8).
    {"glActiveTexture", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glBindImageTexture", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glBindSampler", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glBindTexture", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCompressedTexImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCompressedTexImage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCompressedTexSubImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCompressedTexSubImage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCopyImageSubData", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCopyTexImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCopyTexSubImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glCopyTexSubImage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glDeleteSamplers", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glDeleteTextures", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glFramebufferTexture", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glFramebufferTexture2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glFramebufferTextureLayer", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGenSamplers", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGenTextures", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGenerateMipmap", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetInternalformativ", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetMultisamplefv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetSamplerParameterIiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetSamplerParameterIuiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetSamplerParameterfv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetSamplerParameteriv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexLevelParameterfv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexLevelParameteriv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexParameterIiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexParameterIuiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexParameterfv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glGetTexParameteriv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glIsSampler", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glIsTexture", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glPixelStorei", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameterIiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameterIuiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameterf", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameterfv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameteri", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glSamplerParameteriv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexBuffer", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexBufferRange", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexImage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameterIiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameterIuiv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameterf", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameterfv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameteri", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexParameteriv", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexStorage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexStorage2DMultisample", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glTexStorage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexStorage3DMultisample", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glTexSubImage2D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    {"glTexSubImage3D", "MTLTexture / MTLSamplerState", MappingKind::kDirect,
     "Format gated by ResourcePlan::IsFormatSupported(family); uploads via blit encoder."},
    // Framebuffer / renderbuffer (spec 9).
    {"glBindFramebuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glBindRenderbuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glBlitFramebuffer", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glCheckFramebufferStatus", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glDeleteFramebuffers", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glDeleteRenderbuffers", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glFramebufferParameteri", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glFramebufferRenderbuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glGenFramebuffers", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glGenRenderbuffers", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glGetFramebufferAttachmentParameteriv", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glGetFramebufferParameteriv", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glGetRenderbufferParameteriv", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glInvalidateFramebuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glInvalidateSubFramebuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glIsFramebuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glIsRenderbuffer", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glRenderbufferStorage", "MTLRenderPassDescriptor attachment", MappingKind::kDirect,
     "FBO completeness on CPU; color/depth attachments size the bridge frame."},
    {"glRenderbufferStorageMultisample", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    // Rasterizer / fragment state (spec 13-15).
    {"glBlendColor", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendEquation", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendEquationSeparate", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendEquationSeparatei", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendEquationi", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendFunc", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendFuncSeparate", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendFuncSeparatei", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glBlendFunci", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glColorMask", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glColorMaski", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glCullFace", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glDepthFunc", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glDepthMask", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glDepthRangef", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glDisable", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glDisablei", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glEnable", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glEnablei", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glFrontFace", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glHint", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glIsEnabled", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glIsEnabledi", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glMinSampleShading", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glSampleCoverage", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glSampleMaski", "MTLBlitCommandEncoder / multisample state", MappingKind::kEmulated,
     "Validated CPU-side; multisample resolve not executed in the bridge."},
    {"glScissor", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    {"glStencilFunc", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "Front/back func/ref/mask ride the depth-stencil state + encoder ref value."},
    {"glStencilFuncSeparate", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "Front/back func/ref/mask ride the depth-stencil state + encoder ref value."},
    {"glStencilMask", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "Write masks ride the front/back stencil descriptors."},
    {"glStencilMaskSeparate", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "Write masks ride the front/back stencil descriptors."},
    {"glStencilOp", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "sfail/dpfail/dppass compile to MTLStencilOperation per face."},
    {"glStencilOpSeparate", "MTLDepthStencilState + stencil attachment", MappingKind::kDirect,
     "sfail/dpfail/dppass compile to MTLStencilOperation per face."},
    {"glViewport", "MTLRenderPipelineState / MTLDepthStencilState / viewport/scissor", MappingKind::kDirect,
     "Raster state baked into PsoKeyForDraw (metal_translate enums)."},
    // Sync (spec 4.1).
    {"glClientWaitSync", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glDeleteSync", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glGetInteger64i_v", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glGetInteger64v", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glGetSynciv", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glIsSync", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    {"glWaitSync", "MTLSharedEvent / command-buffer tracking", MappingKind::kDirect,
     "SYNC_GPU_COMMANDS_COMPLETE emulated with frame serials."},
    // Query (spec 4.2).
    {"glBeginQuery", "MTL occlusion query / CPU query state", MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to visibility query; XFB/primitives counted CPU-side."},
    {"glEndQuery", "MTL occlusion query / CPU query state", MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to visibility query; XFB/primitives counted CPU-side."},
    {"glGetQueryObjectuiv", "MTL occlusion query / CPU query state", MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to visibility query; XFB/primitives counted CPU-side."},
    {"glGetQueryiv", "MTL occlusion query / CPU query state", MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to visibility query; XFB/primitives counted CPU-side."},
    {"glIsQuery", "MTL occlusion query / CPU query state", MappingKind::kDirect,
     "ANY_SAMPLES_PASSED maps to visibility query; XFB/primitives counted CPU-side."},
    // Clear / readback (spec 17.3).
    {"glClear", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearBufferfi", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearBufferfv", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearBufferiv", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearBufferuiv", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearColor", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearDepthf", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glClearStencil", "MTLRenderCommandEncoder loadAction", MappingKind::kDirect,
     "Clear values cached in RasterState; applied at pass start."},
    {"glReadPixels", "MTLBlitCommandEncoder / CPU readback", MappingKind::kDirect,
     "ReadPixels validated against READ FBO; bridge BlitToCpu on device."},
    {"glReadnPixels", "MTLBlitCommandEncoder / CPU readback", MappingKind::kDirect,
     "ReadPixels validated against READ FBO; bridge BlitToCpu on device."},
    // Debug / label (spec 18).
    {"glDebugMessageCallback", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glDebugMessageControl", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glDebugMessageInsert", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glGetDebugMessageLog", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glGetObjectLabel", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glGetObjectPtrLabel", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glGetPointerv", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glObjectLabel", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glObjectPtrLabel", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glPopDebugGroup", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    {"glPushDebugGroup", "MTLCaptureManager / CPU label store", MappingKind::kDirect,
     "KHR_debug core; labels stored CPU-side, no encoder."},
    // Server state / misc (spec 20, 2.3).
    {"glDeleteQueries", "CPU state + Metal encoder/PSO", MappingKind::kDirect,
     "Covered by backend PsoKey/CommandPlan/bridge path."},
    {"glFinish", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glFlush", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGenQueries", "CPU state + Metal encoder/PSO", MappingKind::kDirect,
     "Covered by backend PsoKey/CommandPlan/bridge path."},
    {"glGetActiveAttrib", "MTLRenderPipelineState / MTLComputePipelineState + CPU uniform store", MappingKind::kDirect,
     "Program link + uniform reflection on CPU; pipeline compiled from PsoKey."},
    {"glGetBooleani_v", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetBooleanv", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetError", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetFloatv", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetGraphicsResetStatus", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetIntegeri_v", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetIntegerv", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetString", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glGetStringi", "CPU state (no encoder)", MappingKind::kDirect,
     "Query/get/is/finish/flush served from CPU managers; no Metal call."},
    {"glPrimitiveBoundingBox", "CPU hint only", MappingKind::kEmulated,
     "Tessellation bounding-box hint; no Metal encoder state."},
};

const GpuFamilyInfo kFamilies[] = {
    // From Metal-Feature-Set-Tables.pdf (May 21, 2026).
    // BC compression starts at Apple9; mesh shading needs Metal 3 (Apple7+).
    {"Apple3", "A9, A10", true, false, false, false},
    {"Apple4", "A11", true, false, false, false},
    {"Apple5", "A12", true, false, false, false},
    {"Apple6", "A13", true, false, false, false},
    {"Apple7", "A14, M1", true, false, true, true},
    {"Apple8", "A15, A16, M2", true, false, true, true},
    {"Apple9", "A17, A18, M3, M4", true, true, true, true},
    {"Apple10", "A19, M5", true, true, true, true},
};

}  // namespace

const FeatureMapping* MappingTable(std::size_t* out_count) {
  if (out_count) *out_count = sizeof(kMappings) / sizeof(kMappings[0]);
  return kMappings;
}

const FeatureMapping* FindMapping(const char* gles_feature) {
  if (gles_feature == nullptr) return nullptr;
  for (const auto& entry : kMappings) {
    if (std::strcmp(entry.gles_feature, gles_feature) == 0) return &entry;
  }
  return nullptr;
}

const GpuFamilyInfo* GpuFamilyTable(std::size_t* out_count) {
  if (out_count) *out_count = sizeof(kFamilies) / sizeof(kFamilies[0]);
  return kFamilies;
}

const GpuFamilyInfo* FindGpuFamily(const char* family) {
  if (family == nullptr) return nullptr;
  for (const auto& entry : kFamilies) {
    if (std::strcmp(entry.family, family) == 0) return &entry;
  }
  return nullptr;
}

}  // namespace metal
}  // namespace tgles
